import { asTrimmed } from './validation.js'

/**
 * UPI transaction reference (UTR) validation for the direct-UPI payment flow.
 *
 * A UTR is an alphanumeric reference generated by the customer's UPI app. Real
 * UTRs are typically 12–22 characters. Input is normalized (whitespace removed,
 * uppercased) before matching so "abc 1234 xyz" and "abc1234xyz" are the same.
 */

/**
 * Normalize a raw UTR string: trim, strip all internal whitespace, uppercase.
 * Returns null for anything that cannot be treated as a UTR at all.
 */
export function normalizeUtr(value: unknown): string | null {
  if (typeof value !== 'string') return null
  const collapsed = value.replace(/\s+/g, '').trim().toUpperCase()
  return collapsed.length > 0 ? collapsed : null
}

/** UTR length after normalization: 12–22 characters. */
export function isUtrReference(value: unknown): value is string {
  const normalized = normalizeUtr(value)
  return normalized !== null && /^[A-Z0-9]{12,22}$/.test(normalized)
}

/**
 * Optional rejection message for a rejected payment. Trimmed, max 500 chars.
 * Returns null when the field is absent/blank so the caller can omit it.
 */
export function parseRejectionMessage(value: unknown): string | null {
  return asTrimmed(value, 500)
}

/** Max length shared by the client mirror (for consistent hints). */
export const UTR_MAX_LENGTH = 64